// app_localizations.dart
// Static EN/AR localization — no code generation required.

import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  const AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  bool get isAr => locale.languageCode == 'ar';

  static const Map<String, Map<String, String>> _t = {
    'en': {
      'appName': 'PsyCare',
      'appTagline': 'Your Mental Wellness Companion',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full Name',
      'confirmPassword': 'Confirm Password',
      'forgotPassword': 'Forgot Password?',
      'noAccount': "Don't have an account? ",
      'hasAccount': 'Already have an account? ',
      'selectRole': 'I am a...',
      'rolePatient': 'Patient',
      'roleTherapist': 'Therapist',
      'loginSuccess': 'Welcome back!',
      'registerSuccess': 'Account created successfully!',
      'logout': 'Log Out',
      'emailRequired': 'Email is required',
      'emailInvalid': 'Please enter a valid email',
      'passwordRequired': 'Password is required',
      'passwordTooShort': 'Password must be at least 6 characters',
      'nameRequired': 'Name is required',
      'passwordsMismatch': 'Passwords do not match',
      'hello': 'Hello',
      'assessmentSubmitted': 'Assessment Submitted ✓',
      'assessmentPending': 'Assessment Pending',
      'therapistNotified': 'Your therapist has been notified',
      'completeAssessment': 'Complete your assessment to get started',
      'whatToDo': 'What would you like to do?',
      'mentalHealthAssessment': 'Mental Health Assessment',
      'answerQuestions': 'Answer questions about your wellbeing',
      'describeYourFeelings': 'Describe Your Feelings',
      'writeAboutMind': "Write about what's on your mind",
      'aboutPsycare': 'About PsyCare',
      'learnPrivacy': 'Learn how we protect your privacy',
      'talkSomeoneNow': 'Talk to someone now',
      'connectTherapistNow': 'Connect with a therapist right away',
      'availableHours': 'Available 9:00 AM – 10:00 PM',
      'goodDay': 'Good day',
      'totalPatients': 'Total Patients',
      'submitted': 'Submitted',
      'myPatients': 'My Patients',
      'viewAssessments': 'View assessments & AI summaries',
      'aiInsightTip':
          'Use the AI Summarize feature on patient details to get professional insights powered by Groq.',
      'incomingRequests': 'Incoming Requests',
      'patientsWaiting': 'Patients waiting for immediate support',
      'whatBringsYou': 'What brings you here today?',
      'selectAllApply':
          'Select all that apply. This helps us personalize your report.',
      'step1of4': 'Step 1 of 4',
      'selected': 'selected',
      'leave': 'Leave',
      'leaveAssessment': 'Leave assessment?',
      'leaveBody':
          "Your progress will be saved, but the report won't be generated until you finish.",
      'keepGoing': 'Keep going',
      'next': 'Next',
      'youreNotAlone': "You're not alone.",
      'takeYourTime': 'Take your time. What feels right for you right now?',
      'talkNow': 'I need to talk to someone now',
      'talkNowSub': 'Connect with a therapist right away',
      'findTherapist': 'I want to find a therapist',
      'findTherapistSub': 'Browse verified therapists at your own pace',
      'decideLater': "I'll decide later",
      'nextOpenToday': 'today at 9:00 AM',
      'nextOpenTomorrow': 'tomorrow at 9:00 AM',
      'availableFrom':
          "Our support team is available 9:00 AM – 10:00 PM. We'll be here for you",
      'connectingNow': "We're connecting you with\nsomeone now",
      'holdOn':
          "Please hold on — you're not alone.\nA therapist will be with you shortly.",
      'cancel': 'Cancel',
      'yourTherapist': 'Your therapist',
      'sessionActive': 'Session active',
      'sessionEnded': 'Session ended',
      'endSession': 'End',
      'typeMessage': 'Type a message...',
      'bookWithTherapist': 'Book a proper session with this therapist',
      'backToDashboard': 'Back to dashboard',
      'howDidItFeel': 'How did that feel?',
      'bookFollowUp':
          'Would you like to book a proper session with this therapist and continue your journey together?',
      'yesBook': 'Yes, book a session',
      'noDecideLater': "No, I'll decide later",
      'findATherapist': 'Find a Therapist',
      'takYourTime': "Take your time browsing — there's no rush.",
      'searchTherapist': 'Search by name or specialization...',
      'noTherapistsFound': 'No therapists found.',
      'bookSession': 'Book a Session',
      'preferredSessionType': 'Preferred session type',
      'chatSession': 'Chat',
      'videoSession': 'Video Call',
      'inPersonSession': 'In-Person',
      'dataSharingConsent': 'Data sharing consent',
      'consentBody':
          'By confirming this booking, you agree to share your assessment data and AI-generated report with',
      'consentBody2':
          'This information helps your therapist prepare and provide you with the most relevant support from the very first session.',
      'consentCheckbox':
          'I understand and consent to my assessment data being shared with this therapist.',
      'confirmBooking': 'Confirm Booking Request',
      'requestSent': 'Request Sent!',
      'bookingConfirmed': "Your booking request has been sent to",
      'bookingConfirmed2': "You'll hear back once they confirm.",
      'incomingTitle': 'Incoming Requests',
      'incomingSubtitle':
          'Patients in your queue waiting for immediate support.',
      'noPendingRequests': 'No pending requests',
      'pendingEmpty': "When a patient needs immediate help,\nthey'll appear here.",
      'assessmentSummary': 'Assessment summary',
      'acceptConnect': 'Accept & Connect',
      'justNow': 'Just now',
      'minuteAgo': '1 minute ago',
      'minutesAgo': 'minutes ago',
      'hoursAgo': 'h ago',
      'settings': 'Settings',
      'profile': 'Profile',
      'language': 'Language',
      'languageSubtitle': 'Switch between English and Arabic',
      'availability': 'Availability',
      'onShift': 'On Shift',
      'onShiftSub': "You're currently available to patients",
      'availableForImmediate': 'Available for Immediate Chat',
      'availableForImmediateSub':
          'Accept urgent requests from waiting patients',
      'account': 'Account',
      'resetPassword': 'Reset Password',
      'resetPasswordSub': "We'll send a reset link to your email",
      'app': 'App',
      'privacyPolicy': 'Privacy Policy',
      'dangerZone': 'Danger Zone',
      'signOut': 'Sign Out',
      'deleteAccount': 'Delete Account',
      'deleteAccountSub': 'This action cannot be undone',
      'version': 'PsyCare v1.0.0',
      'deleteConfirmTitle': 'Delete account?',
      'deleteConfirmBody':
          'All your data will be permanently deleted. This cannot be undone.',
      'delete': 'Delete',
      'close': 'Close',
      'resetLinkSent': 'Reset link sent to',
      'failedTo': 'Failed:',
      'failedDelete': 'Failed to delete:',
      'loading': 'Loading...',
      'error': 'Something went wrong',
      'retry': 'Retry',
      'save': 'Save',
      'gotIt': 'Got it',
    },
    'ar': {
      'appName': 'PsyCare',
      'appTagline': 'رفيقك للصحة النفسية',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'fullName': 'الاسم الكامل',
      'confirmPassword': 'تأكيد كلمة المرور',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'noAccount': 'ليس لديك حساب؟ ',
      'hasAccount': 'لديك حساب بالفعل؟ ',
      'selectRole': 'أنا...',
      'rolePatient': 'مريض',
      'roleTherapist': 'معالج نفسي',
      'loginSuccess': 'مرحباً بعودتك!',
      'registerSuccess': 'تم إنشاء الحساب بنجاح!',
      'logout': 'تسجيل الخروج',
      'emailRequired': 'البريد الإلكتروني مطلوب',
      'emailInvalid': 'يرجى إدخال بريد إلكتروني صحيح',
      'passwordRequired': 'كلمة المرور مطلوبة',
      'passwordTooShort': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'nameRequired': 'الاسم مطلوب',
      'passwordsMismatch': 'كلمات المرور غير متطابقة',
      'hello': 'مرحباً',
      'assessmentSubmitted': 'تم تقديم التقييم ✓',
      'assessmentPending': 'التقييم معلق',
      'therapistNotified': 'تم إبلاغ معالجك',
      'completeAssessment': 'أكمل تقييمك للبدء',
      'whatToDo': 'ماذا تريد أن تفعل؟',
      'mentalHealthAssessment': 'تقييم الصحة النفسية',
      'answerQuestions': 'أجب على أسئلة حول حالتك',
      'describeYourFeelings': 'صف مشاعرك',
      'writeAboutMind': 'اكتب عما يدور في ذهنك',
      'aboutPsycare': 'عن PsyCare',
      'learnPrivacy': 'اعرف كيف نحمي خصوصيتك',
      'talkSomeoneNow': 'تحدث مع شخص الآن',
      'connectTherapistNow': 'تواصل مع معالج نفسي فوراً',
      'availableHours': 'متاح 9:00 صباحاً – 10:00 مساءً',
      'goodDay': 'يوم سعيد',
      'totalPatients': 'إجمالي المرضى',
      'submitted': 'المُقدَّم',
      'myPatients': 'مرضاي',
      'viewAssessments': 'عرض التقييمات وملخصات الذكاء الاصطناعي',
      'aiInsightTip':
          'استخدم ميزة تلخيص الذكاء الاصطناعي في تفاصيل المريض للحصول على رؤى مهنية مدعومة بـ Groq.',
      'incomingRequests': 'الطلبات الواردة',
      'patientsWaiting': 'مرضى ينتظرون دعماً فورياً',
      'whatBringsYou': 'ما الذي أحضرك إلى هنا اليوم؟',
      'selectAllApply': 'اختر جميع ما ينطبق. سيساعدنا ذلك في تخصيص تقريرك.',
      'step1of4': 'الخطوة 1 من 4',
      'selected': 'مُختار',
      'leave': 'مغادرة',
      'leaveAssessment': 'هل تريد مغادرة التقييم؟',
      'leaveBody':
          'سيتم حفظ تقدمك، لكن لن يتم إنشاء التقرير حتى تنتهي.',
      'keepGoing': 'استمر',
      'next': 'التالي',
      'youreNotAlone': 'أنت لست وحدك.',
      'takeYourTime': 'خذ وقتك. ما الذي يناسبك الآن؟',
      'talkNow': 'أحتاج للتحدث مع شخص الآن',
      'talkNowSub': 'تواصل مع معالج نفسي فوراً',
      'findTherapist': 'أريد إيجاد معالج نفسي',
      'findTherapistSub': 'تصفح المعالجين المعتمدين بوتيرتك',
      'decideLater': 'سأقرر لاحقاً',
      'nextOpenToday': 'اليوم الساعة 9:00 صباحاً',
      'nextOpenTomorrow': 'غداً الساعة 9:00 صباحاً',
      'availableFrom':
          'فريق الدعم متاح من 9:00 صباحاً حتى 10:00 مساءً. سنكون هنا من أجلك',
      'connectingNow': 'نقوم بتوصيلك\nبشخص الآن',
      'holdOn': 'يرجى الانتظار — أنت لست وحدك.\nسيكون المعالج معك قريباً.',
      'cancel': 'إلغاء',
      'yourTherapist': 'معالجك',
      'sessionActive': 'الجلسة نشطة',
      'sessionEnded': 'انتهت الجلسة',
      'endSession': 'إنهاء',
      'typeMessage': 'اكتب رسالة...',
      'bookWithTherapist': 'احجز جلسة رسمية مع هذا المعالج',
      'backToDashboard': 'العودة إلى لوحة التحكم',
      'howDidItFeel': 'كيف شعرت؟',
      'bookFollowUp':
          'هل تريد حجز جلسة رسمية مع هذا المعالج ومواصلة رحلتك معاً؟',
      'yesBook': 'نعم، احجز جلسة',
      'noDecideLater': 'لا، سأقرر لاحقاً',
      'findATherapist': 'ابحث عن معالج نفسي',
      'takYourTime': 'خذ وقتك في التصفح — لا تعجل.',
      'searchTherapist': 'ابحث بالاسم أو التخصص...',
      'noTherapistsFound': 'لا يوجد معالجون.',
      'bookSession': 'حجز جلسة',
      'preferredSessionType': 'نوع الجلسة المفضل',
      'chatSession': 'محادثة',
      'videoSession': 'مكالمة مرئية',
      'inPersonSession': 'حضورياً',
      'dataSharingConsent': 'موافقة على مشاركة البيانات',
      'consentBody':
          'بتأكيد هذا الحجز، توافق على مشاركة بيانات تقييمك وتقريرك مع',
      'consentBody2':
          'تساعد هذه المعلومات معالجك على الاستعداد وتقديم الدعم الأنسب لك من الجلسة الأولى.',
      'consentCheckbox':
          'أفهم وأوافق على مشاركة بيانات تقييمي مع هذا المعالج.',
      'confirmBooking': 'تأكيد طلب الحجز',
      'requestSent': 'تم إرسال الطلب!',
      'bookingConfirmed': 'تم إرسال طلب حجزك إلى',
      'bookingConfirmed2': 'ستتلقى رداً بمجرد تأكيده.',
      'incomingTitle': 'الطلبات الواردة',
      'incomingSubtitle': 'المرضى في قائمة الانتظار يحتاجون دعماً فورياً.',
      'noPendingRequests': 'لا توجد طلبات معلقة',
      'pendingEmpty': 'عندما يحتاج مريض مساعدة فورية،\nسيظهر هنا.',
      'assessmentSummary': 'ملخص التقييم',
      'acceptConnect': 'قبول والاتصال',
      'justNow': 'الآن',
      'minuteAgo': 'منذ دقيقة',
      'minutesAgo': 'دقائق مضت',
      'hoursAgo': 'ساعة مضت',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'language': 'اللغة',
      'languageSubtitle': 'التبديل بين الإنجليزية والعربية',
      'availability': 'التوفر',
      'onShift': 'في الوردية',
      'onShiftSub': 'أنت متاح حالياً للمرضى',
      'availableForImmediate': 'متاح للمحادثة الفورية',
      'availableForImmediateSub': 'قبول الطلبات العاجلة من المرضى المنتظرين',
      'account': 'الحساب',
      'resetPassword': 'إعادة تعيين كلمة المرور',
      'resetPasswordSub': 'سنرسل رابط إعادة التعيين إلى بريدك الإلكتروني',
      'app': 'التطبيق',
      'privacyPolicy': 'سياسة الخصوصية',
      'dangerZone': 'منطقة الخطر',
      'signOut': 'تسجيل الخروج',
      'deleteAccount': 'حذف الحساب',
      'deleteAccountSub': 'لا يمكن التراجع عن هذا الإجراء',
      'version': 'PsyCare v1.0.0',
      'deleteConfirmTitle': 'حذف الحساب؟',
      'deleteConfirmBody':
          'سيتم حذف جميع بياناتك بشكل دائم. لا يمكن التراجع عن هذا.',
      'delete': 'حذف',
      'close': 'إغلاق',
      'resetLinkSent': 'تم إرسال رابط إعادة التعيين إلى',
      'failedTo': 'فشل:',
      'failedDelete': 'فشل الحذف:',
      'loading': 'جارٍ التحميل...',
      'error': 'حدث خطأ ما',
      'retry': 'إعادة المحاولة',
      'save': 'حفظ',
      'gotIt': 'حسناً',
    },
  };

  String tr(String key) =>
      (_t[locale.languageCode] ?? _t['en']!)[key] ?? _t['en']![key] ?? key;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key) => AppLocalizations.of(this).tr(key);
}
